CREATE USER 'aldoco2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdaldoco2_daw;
GRANT ALL PRIVILEGES ON bdaldoco2_daw.* TO 'aldoco2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'armogo2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdarmogo2_daw;
GRANT ALL PRIVILEGES ON bdarmogo2_daw.* TO 'armogo2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'derama2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdderama2_daw;
GRANT ALL PRIVILEGES ON bdderama2_daw.* TO 'derama2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'flgóro2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdflgóro2_daw;
GRANT ALL PRIVILEGES ON bdflgóro2_daw.* TO 'flgóro2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'gabaal2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdgabaal2_daw;
GRANT ALL PRIVILEGES ON bdgabaal2_daw.* TO 'gabaal2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'genoda2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdgenoda2_daw;
GRANT ALL PRIVILEGES ON bdgenoda2_daw.* TO 'genoda2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'gólura2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdgólura2_daw;
GRANT ALL PRIVILEGES ON bdgólura2_daw.* TO 'gólura2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'gópais2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdgópais2_daw;
GRANT ALL PRIVILEGES ON bdgópais2_daw.* TO 'gópais2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'hetaos2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdhetaos2_daw;
GRANT ALL PRIVILEGES ON bdhetaos2_daw.* TO 'hetaos2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'hejija2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdhejija2_daw;
GRANT ALL PRIVILEGES ON bdhejija2_daw.* TO 'hejija2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'lómomi2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdlómomi2_daw;
GRANT ALL PRIVILEGES ON bdlómomi2_daw.* TO 'lómomi2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'lubran2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdlubran2_daw;
GRANT ALL PRIVILEGES ON bdlubran2_daw.* TO 'lubran2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'mámulu2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdmámulu2_daw;
GRANT ALL PRIVILEGES ON bdmámulu2_daw.* TO 'mámulu2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'macaje2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdmacaje2_daw;
GRANT ALL PRIVILEGES ON bdmacaje2_daw.* TO 'macaje2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'mejira2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdmejira2_daw;
GRANT ALL PRIVILEGES ON bdmejira2_daw.* TO 'mejira2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'mecufr2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdmecufr2_daw;
GRANT ALL PRIVILEGES ON bdmecufr2_daw.* TO 'mecufr2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'mevijo2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdmevijo2_daw;
GRANT ALL PRIVILEGES ON bdmevijo2_daw.* TO 'mevijo2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'mubuan2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdmubuan2_daw;
GRANT ALL PRIVILEGES ON bdmubuan2_daw.* TO 'mubuan2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'mumoÁl2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdmumoÁl2_daw;
GRANT ALL PRIVILEGES ON bdmumoÁl2_daw.* TO 'mumoÁl2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'ronúma2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdronúma2_daw;
GRANT ALL PRIVILEGES ON bdronúma2_daw.* TO 'ronúma2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'sáblma2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdsáblma2_daw;
GRANT ALL PRIVILEGES ON bdsáblma2_daw.* TO 'sáblma2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'sásaan2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdsásaan2_daw;
GRANT ALL PRIVILEGES ON bdsásaan2_daw.* TO 'sásaan2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'seleja2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdseleja2_daw;
GRANT ALL PRIVILEGES ON bdseleja2_daw.* TO 'seleja2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'teflal2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdteflal2_daw;
GRANT ALL PRIVILEGES ON bdteflal2_daw.* TO 'teflal2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'vealca2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdvealca2_daw;
GRANT ALL PRIVILEGES ON bdvealca2_daw.* TO 'vealca2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'vegófe2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdvegófe2_daw;
GRANT ALL PRIVILEGES ON bdvegófe2_daw.* TO 'vegófe2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'yujira2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdyujira2_daw;
GRANT ALL PRIVILEGES ON bdyujira2_daw.* TO 'yujira2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE USER 'zablmi2_daw'@'localhost' IDENTIFIED BY 'usuario';
CREATE DATABASE bdzablmi2_daw;
GRANT ALL PRIVILEGES ON bdzablmi2_daw.* TO 'zablmi2_daw'@'localhost' IDENTIFIED BY 'usuario';
